name: hexagram
description: HEXAGRAM
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lunar: ^1.6.1
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.3.2
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
  - family: changingLines
    fonts:
      - asset: lib/iconfonts/changing_lines.ttf
  - family: icomoonFree
    fonts:
      - asset: lib/iconfonts/icomoon_free.ttf

flutter_launcher_icons:
  image_path: "assets/icon/icon_1024.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter_native_splash:
  color: "#daf5ff"