name: Hexagram
description: A solution for hexagram and octochar.
publish_to: 'none'
version: 0.114.514

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lunar: ^1.6.1
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.3.2
  flutter_slidable: ^3.0.0
  path_provider: ^2.1.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
  - family: ChangingLines
    fonts:
      - asset: lib/assets/iconfonts/changing_lines.ttf
  - family: IcomoonFree
    fonts:
      - asset: lib/assets/iconfonts/icomoon_free.ttf
  # - family: SourceHanSerifSC
  #   fonts: 
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-ExtraLight.otf
  #       weight: 100
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-Light.otf
  #       weight: 200
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-Regular.otf
  #       weight: 400
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-Medium.otf
  #       weight: 500
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-SemiBold.otf
  #       weight: 600
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-Bold.otf
  #       weight: 700
  #     - asset: lib/assets/fonts/SourceHanSerifSC/SourceHanSerifSC-Heavy.otf
  #       weight: 900
  # - family: SourceHanSansSC
  #   fonts: 
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-ExtraLight.otf
  #       weight: 100
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-Light.otf
  #       weight: 200
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-Normal.otf
  #       weight: 300
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-Regular.otf
  #       weight: 400
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-Medium.otf
  #       weight: 500
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-Bold.otf
  #       weight: 700
  #     - asset: lib/assets/fonts/SourceHanSansSC/SourceHanSansSC-Heavy.otf
  #       weight: 900
  - family: SimKai
    fonts:
      - asset: lib/assets/fonts/SimKai.ttf
      

flutter_launcher_icons:
  image_path: "lib/assets/icon/icon_1024.png"
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

# flutter_native_splash:
#   color: "#daf5ff"